% Code by René Richter to compile
% important

% Mex_comp = mex.getCompilerConfigurations('c'); Mex_comp.Details
% path_fftw_routine = 'Y:\MATLAB\Toolboxes\matlab_tools\fftw_rft.cpp';
% linked_lib_type = 'libfftw3f-3';
% path_fftw_library = 'C:\Users\pi96doc\Documents\Programming\Lib\libfftw3\'; % fftw-3.3.5-dll64
% %path_fftw_library = 'C:\Users\pi96doc\Documents\Programming\Lib\libfftw3\fftw-3.3.5-dll32';
% mex_command = ['mex ' path_fftw_routine ' -l' linked_lib_type ' -L' path_fftw_library ' -I' path_fftw_library];
% eval(mex_command)
% 

% Important HINT: the library file needs to be generated by the following command
% executed in the shell accesible from the Start -> Visual Studio 2017 -> x64 Native Tools-Eingabeaufforderung
% (the normal shell will not work nor the Visual C shell.)
% lib /machine:x64 /def:libfftw3f-3.def

code by rainer:
mex Y:\MATLAB\Toolboxes\matlab_tools\fftw_rft.cpp -llibfftw3f-3 -LC:\Users\pi96doc\Documents\Programming\Lib\libfftw3\ -IC:\Users\pi96doc\Documents\Programming\Lib\libfftw3\
